application: rokusmug
version: 1-4
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py  

- url: .*
  script: application.py
  
builtins:
- datastore_admin: on
- appstats: on
